# Generated by Django 3.1.6 on 2021-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='user',
            field=models.TextField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
