# Generated by Django 3.1.6 on 2021-02-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210219_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='user',
            field=models.TextField(default=None, max_length=50, null=True),
        ),
    ]
