# Generated by Django 3.1.6 on 2021-02-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210219_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='if_solved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
