# Generated by Django 3.1.6 on 2021-02-19 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210219_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
