# Generated by Django 3.1.6 on 2021-02-19 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_matrix_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
