# Generated by Django 3.1.6 on 2021-02-19 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210219_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
